# -*- coding: utf-8 -*-

from hgt_imports import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(540, 490)

        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")

        self.genshinImg = QLabel(self.centralwidget)
        self.genshinImg.setObjectName(u"genshinImg")
        self.genshinImg.setGeometry(QRect(10, 10, 130, 130))
        self.genshinImg.setPixmap(QPixmap(u"res/ico/genshinico.png"))
        self.genshinImg.setScaledContents(True)

        self.starrailImg = QLabel(self.centralwidget)
        self.starrailImg.setObjectName(u"starrailImg")
        self.starrailImg.setGeometry(QRect(10, 160, 130, 130))
        self.starrailImg.setPixmap(QPixmap(u"res/ico/starrailico.png"))
        self.starrailImg.setScaledContents(True)

        self.zzzImg = QLabel(self.centralwidget)
        self.zzzImg.setObjectName(u"zzzImg")
        self.zzzImg.setGeometry(QRect(10, 310, 130, 130))
        self.zzzImg.setPixmap(QPixmap(u"res/ico/zzzico.png"))
        self.zzzImg.setScaledContents(True)

        self.genshinTimer = QLabel(self.centralwidget)
        self.genshinTimer.setObjectName(u"genshinTimer")
        self.genshinTimer.setGeometry(QRect(300, 10, 220, 30))
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genshinTimer.sizePolicy().hasHeightForWidth())
        self.genshinTimer.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(20)
        self.genshinTimer.setFont(font)
        self.genshinTimer.setCursor(QCursor(Qt.ArrowCursor))
        self.genshinTimer.setTextFormat(Qt.PlainText)
        self.genshinTimer.setScaledContents(False)
        self.genshinTimer.setAlignment(Qt.AlignLeading|Qt.AlignCenter|Qt.AlignVCenter)
        self.genshinTimer.setMargin(1)

        self.starrailTimer = QLabel(self.centralwidget)
        self.starrailTimer.setObjectName(u"starrailTimer")
        self.starrailTimer.setGeometry(QRect(300, 160, 220, 30))
        sizePolicy.setHeightForWidth(self.starrailTimer.sizePolicy().hasHeightForWidth())
        self.starrailTimer.setSizePolicy(sizePolicy)
        self.starrailTimer.setFont(font)
        self.starrailTimer.setCursor(QCursor(Qt.ArrowCursor))
        self.starrailTimer.setTextFormat(Qt.PlainText)
        self.starrailTimer.setScaledContents(False)
        self.starrailTimer.setAlignment(Qt.AlignLeading|Qt.AlignCenter|Qt.AlignVCenter)
        self.starrailTimer.setMargin(1)

        self.zzzTimer = QLabel(self.centralwidget)
        self.zzzTimer.setObjectName(u"zzzTimer")
        self.zzzTimer.setGeometry(QRect(300, 310, 220, 30))
        sizePolicy.setHeightForWidth(self.zzzTimer.sizePolicy().hasHeightForWidth())
        self.zzzTimer.setSizePolicy(sizePolicy)
        self.zzzTimer.setFont(font)
        self.zzzTimer.setCursor(QCursor(Qt.ArrowCursor))
        self.zzzTimer.setTextFormat(Qt.PlainText)
        self.zzzTimer.setScaledContents(False)
        self.zzzTimer.setAlignment(Qt.AlignLeading|Qt.AlignCenter|Qt.AlignVCenter)
        self.zzzTimer.setMargin(1)

        self.genshinInput = QLineEdit(self.centralwidget)
        self.genshinInput.setObjectName(u"genshinInput")
        self.genshinInput.setGeometry(QRect(300, 50, 140, 40))
        self.genshinButton = QPushButton(self.centralwidget)
        self.genshinButton.setObjectName(u"genshinButton")
        self.genshinButton.setGeometry(QRect(450, 50, 80, 40))
        self.genshinChkBox = QCheckBox(self.centralwidget)
        self.genshinChkBox.setObjectName(u"genshin_notify")
        self.genshinChkBox.setGeometry(QRect(300, 90, 200, 40))
        self.genshinChkBox.setText("全快する1時間前に通知する")

        self.starrailInput = QLineEdit(self.centralwidget)
        self.starrailInput.setObjectName(u"starrailInput")
        self.starrailInput.setGeometry(QRect(300, 200, 140, 40))
        self.starrailButton = QPushButton(self.centralwidget)
        self.starrailButton.setObjectName(u"starrailButton")
        self.starrailButton.setGeometry(QRect(450, 200, 80, 40))
        self.starrailChkBox = QCheckBox(self.centralwidget)
        self.starrailChkBox.setObjectName(u"starrail_notify")
        self.starrailChkBox.setGeometry(QRect(300, 240, 200, 40))
        self.starrailChkBox.setText("全快する1時間前に通知する")

        self.zzzInput = QLineEdit(self.centralwidget)
        self.zzzInput.setObjectName(u"zzzInput")
        self.zzzInput.setGeometry(QRect(300, 350, 140, 40))
        self.zzzButton = QPushButton(self.centralwidget)
        self.zzzButton.setObjectName(u"zzzButton")
        self.zzzButton.setGeometry(QRect(450, 350, 80, 40))
        self.zzzChkBox = QCheckBox(self.centralwidget)
        self.zzzChkBox.setObjectName(u"zzz_notify")
        self.zzzChkBox.setGeometry(QRect(300, 390, 200, 40))
        self.zzzChkBox.setText("全快する1時間前に通知する")

        self.gensin_rpb_container = QFrame(self.centralwidget)
        self.gensin_rpb_container.setObjectName(u"gensin_rpb_container")
        self.gensin_rpb_container.setGeometry(QRect(150, 10, 130, 130))
        self.genshin_rpb = RoundProgressBar(self.gensin_rpb_container)
        self.genshin_rpb.setObjectName(u"genshin_rpb")
        self.genshin_rpb.setMinimumSize(QSize(130, 130))
        self.genshin_rpb.setMaximumSize(QSize(130, 130))
        self.genshin_rpb.setInitialPos("North")
        self.genshin_rpb.setTextFormat("Value")

        self.starrail_rpb_container = QFrame(self.centralwidget)
        self.starrail_rpb_container.setObjectName(u"starrail_rpb_container")
        self.starrail_rpb_container.setGeometry(QRect(150, 160, 130, 130))
        self.starrail_rpb = RoundProgressBar(self.starrail_rpb_container)
        self.starrail_rpb.setObjectName(u"starrail_rpb")
        self.starrail_rpb.setMinimumSize(QSize(130, 130))
        self.starrail_rpb.setMaximumSize(QSize(130, 130))
        self.starrail_rpb.setInitialPos("North")
        self.starrail_rpb.setTextFormat("Value")

        self.zzz_rpb_container = QFrame(self.centralwidget)
        self.zzz_rpb_container.setObjectName(u"zzz_rpb_container")
        self.zzz_rpb_container.setGeometry(QRect(150, 310, 130, 130))
        self.zzz_rpb = RoundProgressBar(self.zzz_rpb_container)
        self.zzz_rpb.setObjectName(u"zzz_rpb")
        self.zzz_rpb.setMinimumSize(QSize(130, 130))
        self.zzz_rpb.setMaximumSize(QSize(130, 130))
        self.zzz_rpb.setInitialPos("North")
        self.zzz_rpb.setTextFormat("Value")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.genshinImg.setText("")
        self.starrailImg.setText("")
        self.zzzImg.setText("")
        self.genshinTimer.setText("")
        self.starrailTimer.setText("")
        self.zzzTimer.setText("")
        self.genshinButton.setText(QCoreApplication.translate("MainWindow", u"\u66f4\u65b0", None))
        self.starrailButton.setText(QCoreApplication.translate("MainWindow", u"\u66f4\u65b0", None))
        self.zzzButton.setText(QCoreApplication.translate("MainWindow", u"\u66f4\u65b0", None))
    # retranslateUi

